### ISSUE TITLE
Failed to obtain access token (error after redirect from Google)

### ISSUE THREAD

**Issue by SagarKapasi099** [passport/todos-express-google#2]
Steps to reproduce.
1) npm install
2) create .env file with credentials
3) npm start

![image](https://user-images.githubusercontent.com/26804608/164965285-d720dd9f-8de9-4a73-9d29-76d74a7bc7ba.png)

```
GET /login 304 3.999 ms - -
GET /css/base.css 304 0.495 ms - -
GET /css/index.css 304 0.805 ms - -
GET /css/login.css 304 0.796 ms - -
GET /login/federated/google 302 8.528 ms - 0
GET /oauth2/redirect/google?state=sIZwFahLw%2B3Ovo8bz0Gdpy5C&code=4%2F0AX4XfWgW7XKwwtMnG52Ax4_UsaSUMMyuX-YmggpmT-ua7VEZBFyHo853BfF_i3gby7OGfA&scope=profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=consent 500 310.328 ms - 827
node:_http_outgoing:576
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (/Users/SagarKapasi099/Developer/Mayur/todos-express-google/node_modules/express/lib/response.js:767:10)
    at ServerResponse.location (/Users/SagarKapasi099/Developer/Mayur/todos-express-google/node_modules/express/lib/response.js:884:15)
    at ServerResponse.redirect (/Users/SagarKapasi099/Developer/Mayur/todos-express-google/node_modules/express/lib/response.js:922:18)
    at complete (/Users/SagarKapasi099/Developer/Mayur/todos-express-google/node_modules/passport/lib/middleware/authenticate.js:266:26)
    at /Users/SagarKapasi099/Developer/Mayur/todos-express-google/node_modules/passport/lib/middleware/authenticate.js:278:15
    at pass (/Users/SagarKapasi099/Developer/Mayur/todos-express-google/node_modules/passport/lib/authenticator.js:428:14)
    at Authenticator.transformAuthInfo (/Users/SagarKapasi099/Developer/Mayur/todos-express-google/node_modules/passport/lib/authenticator.js:450:5)
    at /Users/SagarKapasi099/Developer/Mayur/todos-express-google/node_modules/passport/lib/middleware/authenticate.js:275:22 {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by jaredhanson** [comment]
I am unable to reproduce this.  Could you provide more information, such as OS and node version?

**Comment by SagarKapasi099** [comment]
i was using ```node-v16.14.2.pkg```
downgraded to ```node-v16.0.0.pkg```

Working Fine Now. Thanks for your reply.

**Comment by jaredhanson** [comment]
Can you describe what fixed the issue, in case other people land here searching for a solution?

**Comment by jaredhanson** [comment]
Thanks for the info.  I'm unable to reproduce on node v16.14.2, as well.  If you find out further details as to what was causing the issue, please post that information here for others who might be searching for a solution.  Thanks.
